version: 2
updates:
    - package-ecosystem: 'npm'
      # Look for `package.json` and `package-lock.json` files in the `root` directory
      directory: '/'
      schedule:
          interval: 'daily'
