# syntax=docker/dockerfile:experimental

FROM node:24-alpine as base

# ENV NODE_ENV=development
ENV husky_skip_init="1"
ENV HUSKY="0"
ENV HUSKY_DEBUG="1"
#ENV NODE_OPTIONS="--max_old_space_size=4000 --openssl-legacy-provider"
ENV NODE_OPTIONS="--max_old_space_size=4000"

#TODO review env varables

ARG HOST
ENV HOST=${HOST}

ARG CI
ENV CI_ENV=${CI}

WORKDIR /app

FROM base as deps

RUN apk add --no-cache curl python3 py3-setuptools build-base
RUN curl -sf https://gobinaries.com/tj/node-prune | sh
RUN echo "npm cache clean --force && node-prune" > /usr/local/bin/node-clean && chmod +x /usr/local/bin/node-clean

COPY ./package.json /app/package.json
COPY ./package-lock.json /app/package-lock.json
COPY ./packages/admin/package.json /app/packages/admin/package.json
COPY ./packages/scanner/package.json /app/packages/scanner/package.json

RUN --mount=type=cache,sharing=locked,target=/root/.npm \
    npm ci

FROM deps as admin-builder

COPY ./tsconfig.json /app/tsconfig.json
COPY ./packages/admin /app/packages/admin

ARG NEW_API_URL
ENV VITE_NEW_API_URL_ENV=${NEW_API_URL}
ARG APP_VERSION
RUN --mount=type=cache,sharing=locked,target=/root/.npm \
    VITE_APP_VERSION=${APP_VERSION:-$(date +"%Y-%m-%dT%H:%M:%S")} npm --workspace @feed/admin run build

FROM deps as scanner-builder

COPY ./tsconfig.json /app/tsconfig.json
COPY ./packages/scanner /app/packages/scanner

ARG NEW_API_URL
ENV VITE_NEW_API_URL_ENV=${NEW_API_URL}
ARG APP_VERSION
RUN --mount=type=cache,sharing=locked,target=/root/.npm \
    VITE_APP_VERSION=${APP_VERSION:-$(date +"%Y-%m-%dT%H:%M:%S")} npm --workspace @feed/scanner run build

# RUN RUN npm prune --production

# RUN /usr/local/bin/node-clean

FROM base as runner

EXPOSE 80

RUN apk add --no-cache nginx
COPY nginx.conf /etc/nginx/nginx.conf

ARG NEW_API_URL
ENV NEW_API_URL_ENV=${NEW_API_URL}
ARG ADMIN_BASE_PATH
ENV ADMIN_BASE_PATH_ENV=${ADMIN_BASE_PATH}

COPY --from=admin-builder /app/tsconfig.json /app/
COPY --from=admin-builder /app/package.json /app/
COPY --from=admin-builder /app/packages/admin/dist/ /app/packages/admin/dist/

COPY --from=scanner-builder /app/packages/scanner/package.json /app/packages/scanner/
COPY --from=scanner-builder /app/packages/scanner/dist/ /app/packages/scanner/dist/

CMD nginx
