# syntax=docker/dockerfile:1

FROM node:24-alpine AS base

ENV husky_skip_init="1"
ENV HUSKY="0"
ENV NODE_OPTIONS="--max_old_space_size=4000"

WORKDIR /app

FROM base AS deps

RUN apk add --no-cache python3 py3-setuptools build-base

COPY ./package.json /app/package.json
COPY ./package-lock.json /app/package-lock.json
COPY ./packages/admin/package.json /app/packages/admin/package.json
COPY ./packages/scanner/package.json /app/packages/scanner/package.json

RUN --mount=type=cache,sharing=locked,target=/root/.npm \
    npm ci

FROM deps AS admin-builder

COPY ./tsconfig.json /app/tsconfig.json
COPY ./packages/admin /app/packages/admin

ARG NEW_API_URL
ENV VITE_NEW_API_URL_ENV=${NEW_API_URL}
ARG APP_VERSION
RUN --mount=type=cache,sharing=locked,target=/root/.npm \
    --mount=type=cache,target=/app/packages/admin/node_modules/.tmp \
    VITE_APP_VERSION=${APP_VERSION:-$(date +"%Y-%m-%dT%H:%M:%S")} npm --workspace @feed/admin run build

FROM deps AS scanner-builder

COPY ./tsconfig.json /app/tsconfig.json
COPY ./packages/scanner /app/packages/scanner

ARG NEW_API_URL
ENV VITE_NEW_API_URL_ENV=${NEW_API_URL}
ARG APP_VERSION
RUN --mount=type=cache,sharing=locked,target=/root/.npm \
    --mount=type=cache,target=/app/packages/scanner/node_modules/.tmp \
    VITE_APP_VERSION=${APP_VERSION:-$(date +"%Y-%m-%dT%H:%M:%S")} npm --workspace @feed/scanner run build

FROM nginx:1.29-alpine AS runner

EXPOSE 80

COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=admin-builder /app/packages/admin/dist/ /app/packages/admin/dist/
COPY --from=scanner-builder /app/packages/scanner/dist/ /app/packages/scanner/dist/

CMD ["nginx"]
