services:
  jaeger:
    image: jaegertracing/jaeger:${JAEGER_VERSION:-latest}
    volumes:
      - ../db/jaeger_data:/tmp/jaeger
      - "./jaeger-ui.json:/etc/jaeger/jaeger-ui.json" # Do we need this for v2 ? Seems to be running without this.
      - "./config-spm.yaml:/etc/jaeger/config.yml"
    command: [ "--config", "/etc/jaeger/config.yml" ]
    ports:
      - "16686:16686"
      - "8888:8888"
      - "8889:8889"
      - "4317:4317"
      - "4318:4318"

  hotrod:
    image: ${REGISTRY:-}jaegertracing/example-hotrod:${HOTROD_VERSION:-latest}
    ports:
      - "8080:8080"
      - "8083:8083"
    command: [ "all" ]
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
    depends_on:
      - jaeger

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
