# Generated by Django 4.2.11 on 2024-04-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField()),
                ('status', models.CharField(choices=[('inserted', 'inserted'), ('updated', 'updated'), ('deleted', 'deleted')], max_length=16)),
                ('object', models.CharField(max_length=32)),
                ('actor_badge', models.UUIDField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'История',
            },
        ),
    ]
