# Generated by Django 4.2.11 on 2024-04-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='date',
            new_name='action_at',
        ),
        migrations.AlterField(
            model_name='history',
            name='actor_badge',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
