# Generated by Django 4.2.11 on 2024-05-17 18:10

from django.db import migrations

from history.models import History


def del_all_history(self, schema_editor):
    History.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_rename_date_history_action_at_and_more'),
    ]

    operations = [
        migrations.RunPython(del_all_history),
        migrations.RemoveField(
            model_name='history',
            name='object_id',
        ),
    ]
