# Generated by Django 4.2.11 on 2024-05-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_rename_date_history_action_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='object_id',
        ),
    ]
