# Generated by Django 4.2.11 on 2024-05-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_remove_history_object_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='object',
            new_name='object_name',
        ),
        migrations.AddField(
            model_name='history',
            name='old_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
