# Generated by Django 4.2.11 on 2024-06-03 18:47

from django.db import migrations, models

from history.models import History


def del_all_history(self, schema_editor):
    History.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_rename_object_history_object_name_history_old_data'),
    ]

    operations = [
        migrations.RunPython(del_all_history),
        migrations.AddField(
            model_name='history',
            name='volunteer_uuid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
