# Generated by Django 4.2.13 on 2024-06-10 13:23

from django.db import migrations, models
import history.models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_history_volunteer_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='data',
            field=models.JSONField(blank=True, encoder=history.models.UUIDEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='old_data',
            field=models.JSONField(blank=True, encoder=history.models.UUIDEncoder, null=True),
        ),
    ]
