# Generated by Django 5.1.6 on 2025-04-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_alter_history_data_alter_history_old_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='group_operation_uuid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
