# Generated by Django 5.2.3 on 2026-03-21 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeder', '0071_alter_groupbadgeplanningcells_meal_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(default=None, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Storage',
                'verbose_name_plural': 'Storages',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(default=None, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, help_text='Optional identifier', max_length=64, null=True)),
                ('is_unique', models.BooleanField(default=False, help_text='True for items that exist only once (count always 1)')),
                ('metadata', models.JSONField(blank=True, help_text='Free‑form data for the item', null=True)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'unique_together': {('name', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(default=None, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField(blank=True, help_text='Optional maximum item count for the bin', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='storage.storage')),
            ],
            options={
                'verbose_name': 'Bin',
                'verbose_name_plural': 'Bins',
                'unique_together': {('storage', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StorageItemPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(default=None, editable=False, null=True)),
                ('count', models.IntegerField(help_text='1 for unique items, >0 for non‑unique')),
                ('description', models.TextField(blank=True, null=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='storage.bin')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='storage.item')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='storage.storage')),
            ],
            options={
                'verbose_name': 'Storage Item Position',
                'verbose_name_plural': 'Storage Item Positions',
                'unique_together': {('storage', 'bin', 'item')},
            },
        ),
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(default=None, editable=False, null=True)),
                ('count', models.IntegerField(help_text='Number of items received')),
                ('notes', models.TextField(blank=True, null=True)),
                ('volunteer', models.ForeignKey(help_text='Who delivered the items', on_delete=django.db.models.deletion.PROTECT, related_name='receivings', to='feeder.volunteer')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivings', to='storage.storageitemposition')),
            ],
            options={
                'verbose_name': 'Receiving',
                'verbose_name_plural': 'Receivings',
            },
        ),
        migrations.CreateModel(
            name='Issuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(default=None, editable=False, null=True)),
                ('count', models.IntegerField(help_text='For non‑unique items this is the issued amount; for unique items always 1')),
                ('notes', models.TextField(blank=True, null=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuances', to='feeder.volunteer')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuances', to='storage.storageitemposition')),
            ],
            options={
                'verbose_name': 'Issuance',
                'verbose_name_plural': 'Issuances',
            },
        ),
    ]
