# Generated by Django 5.2.3 on 2026-03-21 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0071_alter_groupbadgeplanningcells_meal_time'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='issuance',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issuances', to='feeder.volunteer'),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivings', to='feeder.volunteer'),
        ),
    ]
