# Generated by Django 5.2.3 on 2026-04-11 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_item_is_anonymous_alter_issuance_volunteer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='storage.storage'),
        ),
    ]
