# Generated by Django 5.2.3 on 2026-05-16 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0076_merge_20260509_1502'),
        ('storage', '0003_add_storage_to_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('count', models.IntegerField()),
                ('from_volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_storage_movements', to='feeder.volunteer')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='storage.storageitemposition')),
                ('to_volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_storage_movements', to='feeder.volunteer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VolunteerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('count', models.IntegerField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='volunteer_inventory', to='storage.storageitemposition')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_inventory', to='feeder.volunteer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('volunteer', 'position'), name='unique_volunteer_inventory_position')],
            },
        ),
    ]
