# Generated by Django 5.2.3 on 2026-05-17 00:06

from django.db import migrations
from django.db.models import Sum


def populate_volunteer_inventory(apps, schema_editor):
    Issuance = apps.get_model('storage', 'Issuance')
    VolunteerInventory = apps.get_model('storage', 'VolunteerInventory')
    db_alias = schema_editor.connection.alias

    inventory_rows = (
        Issuance.objects.using(db_alias)
        .filter(deleted_at__isnull=True, volunteer_id__isnull=False, position__item__is_anonymous=False)
        .values('volunteer_id', 'position_id')
        .annotate(total_count=Sum('count'))
        .filter(total_count__gt=0)
    )

    VolunteerInventory.objects.using(db_alias).bulk_create(
        [
            VolunteerInventory(
                volunteer_id=row['volunteer_id'],
                position_id=row['position_id'],
                count=row['total_count']
            )
            for row in inventory_rows
        ]
    )


def clear_volunteer_inventory(apps, schema_editor):
    VolunteerInventory = apps.get_model('storage', 'VolunteerInventory')
    VolunteerInventory.objects.using(schema_editor.connection.alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_movement_volunteerinventory'),
    ]

    operations = [
        migrations.RunPython(populate_volunteer_inventory, clear_volunteer_inventory),
    ]
