# Generated by Django 5.2.3 on 2026-05-24 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0077_merge_20260511_1208'),
        ('storage', '0005_populate_volunteer_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuance',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_issuance_actions', to='feeder.volunteer'),
        ),
        migrations.AddField(
            model_name='movement',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_movement_actions', to='feeder.volunteer'),
        ),
        migrations.AddField(
            model_name='receiving',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_receiving_actions', to='feeder.volunteer'),
        ),
    ]
