# Generated by Django 5.2.3 on 2026-06-28 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_issuance_actor_movement_actor_receiving_actor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sku',
        ),
    ]
