# Generated by Django 4.2.1 on 2024-04-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SynchronizationToSystemActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('notion', 'notion')], max_length=32)),
                ('date', models.DateTimeField()),
                ('latest', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Синхронизация В',
                'verbose_name_plural': 'Синхронизация В',
            },
        ),
    ]
