# Generated by Django 4.2.11 on 2024-05-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SynchronizationSystemActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('notion', 'notion')], max_length=32)),
                ('direction', models.CharField(choices=[('to_system', 'to_system'), ('from_system', 'from_system')], max_length=32)),
                ('date', models.DateTimeField()),
                ('latest', models.BooleanField(default=False)),
                ('success', models.BooleanField(default=True)),
                ('error', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'verbose_name': 'Синхронизация В',
                'verbose_name_plural': 'Синхронизация В',
            },
        ),
        migrations.DeleteModel(
            name='SynchronizationToSystemActions',
        ),
    ]
