# Generated by Django 4.2.11 on 2024-06-03 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synchronization', '0002_synchronizationsystemactions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='synchronizationsystemactions',
            options={'verbose_name': 'Синхронизация', 'verbose_name_plural': 'Синхронизация'},
        ),
    ]
