# Generated by Django 5.2.3 on 2025-06-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronization', '0003_alter_synchronizationsystemactions_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='synchronizationsystemactions',
            name='partial_offset',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
