# Generated by Django 5.2.3 on 2026-06-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronization', '0004_synchronizationsystemactions_partial_offset'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='synchronizationsystemactions',
            index=models.Index(fields=['system', 'direction', '-date', '-id'], name='sync_sys_dir_date_idx'),
        ),
        migrations.AddIndex(
            model_name='synchronizationsystemactions',
            index=models.Index(condition=models.Q(('success', True)), fields=['system', 'direction', '-date', '-id'], name='sync_sys_dir_ok_date_idx'),
        ),
    ]
