version: "3.4"

services:
  nginx:
    build: .
    container_name: ins_nginx_local
    restart: always
    environment:
      - HTTPS_METHOD=noredirect
    ports:
      - "80:80"
#      - "443:443"
    volumes:
      - ./log/:/var/log/nginx
      - ./nginx:/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
