FROM node:18-alpine

ENV NODE_OPTIONS="--max_old_space_size=4000"

WORKDIR /app

RUN apk add --no-cache python3 build-base libffi-dev
RUN curl -sf https://gobinaries.com/tj/node-prune | sh
RUN echo "npm cache clean --force && node-prune" > /usr/local/bin/node-clean && chmod +x /usr/local/bin/node-clean

COPY ./package.json /app/package.json
COPY ./package-lock.json /app/package-lock.json

COPY ./packages/admin/package.json /app/packages/admin/package.json
COPY ./packages/scanner/package.json /app/packages/scanner/package.json

RUN --mount=type=cache,sharing=locked,target=/root/.npm \
    npm ci

COPY . /app

EXPOSE 3001
EXPOSE 3002
