# Generated by Django 4.2.1 on 2023-06-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0007_volunteer_badge_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedtransaction',
            name='is_vegan',
            field=models.BooleanField(null=True, verbose_name='Вегетарианец?'),
        ),
    ]
