# Generated by Django 4.2.1 on 2023-06-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0007_volunteer_badge_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedtransaction',
            name='qr_code',
            field=models.CharField(max_length=255, null=True, verbose_name='QR код'),
        ),
    ]
