# Generated by Django 4.2.1 on 2023-06-16 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feeder", "0008_alter_feedtransaction_is_vegan"),
        ("feeder", "0008_groupbadge_volunteer_group_badge"),
    ]

    operations = []
