# Generated by Django 4.2.1 on 2023-06-17 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("feeder", "0009_merge_20230616_1504"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="group_badge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="feeder.groupbadge",
                verbose_name="Групповой бейдж",
            ),
        ),
    ]
