# Generated by Django 4.2.1 on 2024-01-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0011_volunteer_printing_batch_volunteer_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Кастомное поле волонтера',
                'verbose_name_plural': 'Кастомные поля волонтера',
            },
        ),
    ]
