# Generated by Django 4.2.1 on 2024-01-23 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0013_volunteercustomfield_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('value', models.TextField(verbose_name='Значение')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeder.volunteercustomfield', verbose_name='Кастомное поле')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='feeder.volunteer', verbose_name='Волонтер')),
            ],
            options={
                'verbose_name': 'Значение кастомного поля волонтера',
                'verbose_name_plural': 'Значения кастомных полей волонтера',
            },
        ),
    ]
