# Generated by Django 4.2.1 on 2024-01-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0014_volunteercustomfieldvalue'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='volunteercustomfieldvalue',
            constraint=models.UniqueConstraint(fields=('volunteer', 'custom_field'), name='unique fields'),
        ),
    ]
