# Generated by Django 4.2.1 on 2024-04-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0018_alter_volunteer_directions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
