# Generated by Django 4.2.1 on 2024-04-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0019_rename_lastname_volunteer_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='name',
            new_name='first_name',
        ),
    ]
