# Generated by Django 4.2.1 on 2024-04-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0021_rename_nickname_volunteer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя на бейдже'),
        ),
    ]
