# Generated by Django 4.2.1 on 2024-04-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0022_alter_volunteer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
    ]
