# Generated by Django 4.2.1 on 2024-04-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0026_alter_arrival_id_alter_direction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementrole',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
    ]
