# Generated by Django 4.2.1 on 2024-04-08 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0027_alter_engagementrole_id_alter_transport_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='feeder.person'),
        ),
    ]
