# Generated by Django 4.2.1 on 2024-04-10 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0028_alter_engagement_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrival',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='feeder.volunteer'),
        ),
    ]
