# Generated by Django 4.2.11 on 2024-04-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0028_alter_engagement_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='deleted_at',
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
    ]
