# Generated by Django 4.2.1 on 2024-04-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0029_alter_arrival_volunteer'),
    ]

    operations = [
        migrations.RunSQL(
            sql='insert into feeder_arrival(id, volunteer_id, created_at, updated_at, arrival_date, departure_date) select uuid, id, created_at, updated_at, DATE(DATETIME(active_from, \'+3 hours\')), DATE(DATETIME(active_to, \'+3 hours\')) from feeder_volunteer where active_from is not null and active_to is not null',
            reverse_sql='delete from feeder_arrival'
        )
    ]
