# Generated by Django 4.2.1 on 2024-05-03 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0029_volunteer_deleted_at'),
        ('feeder', '0030_auto_20240410_1549'),
    ]

    operations = [
    ]
