# Generated by Django 4.2.1 on 2024-05-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0033_alter_directiontype_id_alter_volunteerrole_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='notion_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
