# Generated by Django 4.2.13 on 2024-06-09 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0036_volunteer_direction_head_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='role',
        ),
    ]
