# Generated by Django 4.2.1 on 2024-06-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0037_groupbadge_direction'),
        ('feeder', '0037_remove_volunteer_role'),
    ]

    operations = [
    ]
