# Generated by Django 4.2.13 on 2024-06-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0038_merge_20240612_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='notion_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
