# Generated by Django 4.2.13 on 2024-06-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0039_alter_engagement_notion_id'),
        ('feeder', '0039_remove_old_direction_types'),
    ]

    operations = [
    ]
