# Generated by Django 4.2.1 on 2024-09-04 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0041_auto_20240617_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='lead',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='active_from',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='active_to',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='daily_eats',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='ref_to',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
