# Generated by Django 4.2.1 on 2024-10-30 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0043_volunteercustomfield_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='group_badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteers', to='feeder.groupbadge', verbose_name='Групповой бейдж'),
        ),
    ]
