# Generated by Django 5.1.3 on 2024-11-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0044_alter_volunteer_group_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='is_ticket_received',
            field=models.BooleanField(default=False, verbose_name='Выдан ли билет?'),
        ),
    ]
