# Generated by Django 5.1.2 on 2024-11-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0045_volunteer_is_ticket_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='scanner_comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий при сканировании'),
        ),
    ]
