# Generated by Django 5.1 on 2024-11-17 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeder", "0045_volunteer_is_ticket_received"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedtransaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="feeder.person",
            ),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="is_child",
            field=models.BooleanField(blank=True, null=True, verbose_name="IsChild"),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="responsible_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="volunteers",
                to="feeder.volunteer",
                verbose_name="Ответственный",
            ),
        ),
    ]
