# Generated by Django 4.2.1 on 2024-11-19 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0046_volunteer_scanner_comment'),
        ('feeder', '0047_alter_volunteer_is_child'),
    ]

    operations = [
    ]
