# Generated by Django 4.2.1 on 2025-01-09 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0049_remove_feedtransaction_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedtransaction',
            name='created_by',
        ),
    ]
