# Generated by Django 5.1 on 2025-01-29 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feeder", "0050_remove_feedtransaction_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="volunteer",
            name="color_type",
        ),
    ]
