# Generated by Django 5.1 on 2025-03-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeder", "0051_remove_volunteer_color_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="VolunteerGroupOperation",
            fields=[
                (
                    "group_operation_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("volunteers_ids", models.JSONField()),
                ("original_data", models.JSONField()),
                ("new_data", models.JSONField()),
            ],
            options={
                "verbose_name": "Групповая операция",
                "verbose_name_plural": "Групповые операции",
            },
        ),
    ]
