# Generated by Django 4.2.1 on 2025-03-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0052_wash'),
    ]

    operations = [
        migrations.AddField(
            model_name='wash',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='wash',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
