# Generated by Django 5.1 on 2025-03-09 21:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeder", "0055_volunteergroupoperation_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteergroupoperation",
            name="group_operation_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
