# Generated by Django 4.2.1 on 2025-04-06 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0056_alter_volunteergroupoperation_group_operation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='notion_id',
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='notion_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='notion_id',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='notion_id',
        ),
    ]
