# Generated by Django 5.1.7 on 2025-05-31 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0057_remove_direction_notion_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='photo_local',
            field=models.TextField(blank=True, null=True, verbose_name='Загруженная фотография'),
        ),
    ]
