# Generated by Django 4.2.1 on 2025-05-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0058_wash_washcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wash',
            old_name='washCount',
            new_name='wash_count',
        ),
    ]
