# Generated by Django 4.2.1 on 2025-06-03 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0058_volunteer_photo_local'),
        ('feeder', '0059_rename_washcount_wash_wash_count'),
    ]

    operations = [
    ]
