# Generated by Django 4.2.1 on 2025-06-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0060_merge_20250603_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='deleted_at',
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
    ]
