# Generated by Django 4.2.1 on 2025-06-13 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0061_person_deleted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='is_child',
            new_name='infant',
        ),
    ]
