# Generated by Django 5.1.7 on 2025-06-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0061_person_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='is_photo_updated',
            field=models.BooleanField(default=False, verbose_name='Фото обновлено?'),
        ),
    ]
