# Generated by Django 4.2.1 on 2025-06-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0062_rename_is_child_volunteer_infant'),
        ('feeder', '0062_volunteer_is_photo_updated'),
    ]

    operations = [
    ]
