# Generated by Django 4.2.1 on 2025-06-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0063_merge_20250615_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='is_ticket_received',
            field=models.BooleanField(default=False, null=True, verbose_name='Выдан ли билет?'),
        ),
    ]
