# Generated by Django 5.2.1 on 2025-06-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0064_alter_volunteer_is_ticket_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='is_baged_leader',
            field=models.BooleanField(default=False, null=True, verbose_name='Бейдж у Руководителя'),
        ),
    ]
