# Generated by Django 5.2.9 on 2025-12-21 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0064_alter_volunteer_is_ticket_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='supervisor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisees', to='feeder.volunteer', verbose_name='Бригадир'),
        ),
    ]
