# Generated by Django 5.1.7 on 2026-02-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeder", "0065_volunteer_supervisor_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupbadge",
            name="deleted_at",
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
    ]
