# Generated by Django 5.2.9 on 2026-02-28 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0065_volunteer_supervisor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbadge',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='feeder.volunteerrole'),
        ),
    ]
