# Generated by Django 5.2.9 on 2026-02-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0065_volunteer_supervisor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedtransaction',
            name='is_anomaly',
            field=models.BooleanField(default=False, verbose_name='Аномалия?'),
        ),
    ]
