# Generated by Django 5.2.11 on 2026-02-23 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0065_volunteer_supervisor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBadgePlanningCells',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount_meat', models.SmallIntegerField(null=True, verbose_name='Количество мясоедов')),
                ('amount_vegan', models.SmallIntegerField(null=True, verbose_name='Количество вегетарианцев')),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_badge_planning_cells', to='feeder.feedtype', verbose_name='Тип питания')),
                ('group_badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_badge_planning_cells', to='feeder.groupbadge')),
            ],
            options={
                'verbose_name': 'Ячейка планирования питания группового бейджа',
                'verbose_name_plural': 'Ячейки планирования питания групповых бейджей',
                'constraints': [models.UniqueConstraint(fields=('group_badge', 'feed_type', 'date'), name='unique planning cell')],
            },
        ),
    ]
