# Generated by Django 5.2.9 on 2026-02-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0066_groupbadge_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerrole',
            name='is_group_badge',
            field=models.BooleanField(default=False),
        ),
    ]
