# Generated by Django 5.1.7 on 2026-02-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeder", "0066_groupbadge_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupbadge",
            name="qr",
            field=models.TextField(
                blank=True, null=True, unique=True, verbose_name="QR-код"
            ),
        ),
    ]
