# Generated by Django 5.2.3 on 2026-03-01 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0066_feedtransaction_is_anomaly'),
        ('feeder', '0067_volunteerrole_is_group_badge'),
    ]

    operations = [
    ]
