# Generated by Django 5.2.3 on 2026-03-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0066_groupbadgeplanningcells'),
        ('feeder', '0067_alter_groupbadge_qr'),
        ('feeder', '0068_merge_20260301_1104'),
    ]

    operations = [
    ]
