# Generated by Django 5.2.10 on 2026-03-15 22:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0069_merge_20260301_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidArrival',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('is_free', models.BooleanField()),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_arrivals', to='feeder.volunteer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
