# Generated by Django 5.2.10 on 2026-03-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0069_merge_20260301_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedtransaction',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Платное питание?'),
        ),
    ]
