# Generated by Django 5.2.3 on 2026-03-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0070_feedtransaction_is_paid'),
        ('feeder', '0070_paidarrival'),
    ]

    operations = [
    ]
