# Generated by Django 5.2.3 on 2026-03-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0070_feedtransaction_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbadgeplanningcells',
            name='meal_time',
            field=models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('night', 'night')], max_length=10, verbose_name='Время питания'),
        ),
    ]
