# Generated by Django 5.2.11 on 2026-03-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0071_merge_0070_feedtransaction_is_paid_0070_paidarrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='approver',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Утвердивший'),
        )
    ]
