# Generated by Django 5.2.3 on 2026-04-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0071_merge_0070_feedtransaction_is_paid_0070_paidarrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='banned',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
