# Generated by Django 5.2.3 on 2026-04-06 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0071_alter_groupbadgeplanningcells_meal_time'),
        ('feeder', '0071_merge_0070_feedtransaction_is_paid_0070_paidarrival'),
    ]

    operations = [
    ]
