# Generated by Django 5.2.3 on 2026-04-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0072_person_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='is_badge_located_at_leader',
            field=models.BooleanField(default=False, verbose_name='Бейдж у руководителя?'),
        ),
    ]
