# Generated by Django 5.2.3 on 2026-04-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0072_merge_20260406_1807'),
        ('feeder', '0072_person_banned'),
    ]

    operations = [
    ]
