# Generated by Django 5.2.3 on 2026-04-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0073_merge_0072_merge_20260406_1807_0072_person_banned'),
        ('feeder', '0073_volunteer_is_badge_located_at_leader'),
    ]

    operations = [
    ]
