# Generated by Django 5.2.3 on 2026-05-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0074_merge_20260426_1337'),
    ]

    operations = [
        migrations.RunSQL(
            sql="update feeder_volunteerrole set name = 'Автор', is_group_badge = true where id = 'ANIMATOR'",
            reverse_sql="update feeder_volunteerrole set name = 'Аниматор', is_group_badge = true where id = 'ANIMATOR'",
        ),
        migrations.RunSQL(
            sql="update feeder_volunteerrole set is_group_badge = true where id = 'LECTOR'",
            reverse_sql="update feeder_volunteerrole set is_group_badge = false where id = 'LECTOR'",
        ),
    ]
