# Generated by Django 5.2.3 on 2026-05-03 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0074_merge_20260426_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbadge',
            name='kitchen',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='feeder.kitchen',
                verbose_name='Кухня',
            ),
        ),
    ]
