# Generated by Django 5.2.11 on 2026-05-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0075_groupbadge_kitchen'),
        ('feeder', '0075_update_group_badge_roles'),
    ]

    operations = [
    ]
