# Generated by Django 5.2.11 on 2026-05-11 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0072_volunteer_approver'),
        ('feeder', '0076_merge_20260509_1502'),
    ]

    operations = [
    ]
