# Generated by Django 5.2.3 on 2026-06-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0078_set_default_groupbadge_kitchen'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbadge',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='Выключен'),
        ),
    ]
