name: Lint

on:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Lint JavaScript
              run: npm run lint:js
            - name: Lint TypeScript
              run: npm run lint:ts
            - name: Lint Style
              run: npm run lint:css
