import type { Action, IResourceItem } from '@refinedev/core';

const APP_TITLE = 'Feed Admin';

const actionTitles: Partial<Record<Action, string>> = {
    list: '',
    create: 'Создать',
    edit: 'Редактировать',
    show: 'Просмотр',
    clone: 'Клонировать'
};

export const buildDocumentTitle = ({
    action,
    autoGeneratedTitle,
    resource
}: {
    action?: Action;
    autoGeneratedTitle: string;
    resource?: IResourceItem;
}) => {
    const label = typeof resource?.meta?.label === 'string' ? resource.meta.label : undefined;

    if (!label) {
        return autoGeneratedTitle;
    }

    const actionTitle = action ? actionTitles[action] : undefined;

    if (!actionTitle) {
        return `${label} | ${APP_TITLE}`;
    }

    return `${actionTitle}: ${label} | ${APP_TITLE}`;
};
